### ISSUE TITLE
The settings on IRNet

### ISSUE THREAD

**Issue by Italy2006** [yoon307/CTI#3]
Thanks for your work. Could you provide the corresponding settings for training IRNet? Thanks !

**Comment by yoon307** [comment]
fg-bg threshold is set to 0.4/0.26. However, since the original IRNet doesn't support the ViT (extracting CAMs), you need to implement the CAMs extraction part. I will also update IRN code in the near future.

**Comment by Italy2006** [comment]
> fg-bg threshold is set to 0.4/0.26. However, since the original IRNet doesn't support the ViT (extracting CAMs), you need to implement the CAMs extraction part. I will also update IRN code in the near future.

Hello，may I ask when you intend to release the code about VIT based IRN?? Thank you!
