### ISSUE TITLE
train/infer on COCO？Segmentation reference？

### ISSUE THREAD

**Issue by HYTHYThythyt** [yoon307/CTI#6]
Hi, author. Thank you for your great job.
And, I wnat to know that how to train on COCO, also how to infer the final mask on COCO?
Could you release the segmentation codes and the codes on COCO dataset?
Thank you very much!

**Comment by HYTHYThythyt** [comment]
And the Irn codes also have not found in this codes.

**Comment by yoon307** [comment]
Sorry for the late response. I updated COCO training code (but not yet fully checked cuz this CTI branch is separated from the other work (DiG,ECCV24), If there is an error, let me know. For the IRN, I've been busy, so I can only send you some crucial parts of IRN via email. (send code request to:  yoon307@kaist.ac.kr)
