### ISSUE TITLE
About VisionTransformer_ysh

### ISSUE THREAD

**Issue by buchannn** [yoon307/CTI#7]
The module "networks.vision_transformer" imports VisionTransformer, _cfg, and VisionTransformer_ysh, but there is no code related to VisionTransformer_ysh within "networks.vision_transformer".

How might this issue be resolved?

**Comment by yoon307** [comment]
Sorry for the late response. Since "VisionTransformer_ysh" is not used throughout the entire codebase, I update (deleted) that one.
